### ISSUE TITLE
Direct Export Templating

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#10]
It should be possible to directly create export values based on imports with the templating mechanism.

This is needed because a export that is just constructed out of imports or is defaulted and the value is then exported, this value would have to be somewhere in a deploy item and then read from there.

As this workaround is error prone and hard to understand, it should be possible to either
- template export in the `deployExecutions` section.
- have access to imports in the `exportExecutions`

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
