### ISSUE TITLE
Have init container load and mount terraform providers from OCI registry

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#123]
**How to categorize this issue?**

/area operations
/kind enhancement
/priority normal

**What would you like to be added**:
- Terraform provider plugins need to be listed in the component descriptor
- an init container downloads these and mounts them before the terraformer is run

**Why is this needed**:
As discussed in https://github.com/gardener/terraformer/issues/74, the way we are currently using the terraformer limits the terraform deployer in its capabilities. Dynamically downloading the terraform providers is not desirable, as it causes problems in restricted environments, therefore we would like to solve the problem by providing the necessary terraform providers as artifacts in an OCI registry and handle them like the other dependencies by referencing them in the component descriptor. An init container will then download them and mount them into the terraformer container when the terraform deployer is run.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
