### ISSUE TITLE
Pass RegistryPullSecrets to DeployItems

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#125]
**How to categorize this issue?**

/area deployers
/kind enhancement
/priority normal

**What would you like to be added**:

Currently it is possible to set `registryPullSecrets` on Installations to specify registry secrets for Component Descriptors and blueprints.
These secrets are only used in the landscaper but are not available for deployers.
As deployers also need access to the registry (helm charts, component descriptors or other resources) these secrets should also be passed to the deployers.

Therefore, we would need to enhance the `DeployItem` CR and add a optional `registryPullSecrets` attribute.

**Comment by loewenstein** [comment]
@schrodit Quick question: Is it correct that the `registryPullSecrets` need to be passed through `Execution` CRs, in oder to be written to the `DeployItems` or is there some other way I couldn't immediately see in the code?

I.e. would we [pass the secret ref to the `DeployItemTemplate` of an `Execution`](https://github.com/gardener/landscaper/blob/9f4fe1b3ec92a32380ae87b2343eb9c07527bfdd/pkg/landscaper/installations/executions/operation.go#L76) and then [pass the secret ref from `DeployItemTemplate` on to the `DeployItem`](https://github.com/gardener/landscaper/blob/9f4fe1b3ec92a32380ae87b2343eb9c07527bfdd/pkg/landscaper/execution/reconcile.go#L108)?

**Comment by schrodit** [comment]
>  Is it correct that the registryPullSecrets need to be passed through Execution CRs, in oder to be written to the DeployItems or is there some other way I couldn't immediately see in the code?
Yes that would be the corect way. The secret refs would need to be passed to the execution and from there to the deployitems.
I would not expose that option in the blueprint template as we would mix build time dependencies defined via imports or the component descriptor and runtime dependencies like registry secrets
