### ISSUE TITLE
Container/Shell Executor

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#135]
**How to categorize this issue?**

/area landscaper
/kind enhancement
/priority normal

**What would you like to be added**:

Currently it is only possible to template deployitems using gotemplate or spiff.
To be more flexible and also support other templating engines a generic container/shell executor can be used to support such use cases.

The idea is to use the same mechanism as in the container deployer so that the imports and blueprint + cd is mounted to the container.
When finished, the deployitem templates is written to a specific path where it is then taken by the landscaper for further processing.

**Comment by loewenstein** [comment]
@schrodit could we also start supporting `dir` in addition to `file` to reference to deploy and export execution templates?

**Comment by schrodit** [comment]
> @schrodit could we also start supporting `dir` in addition to `file` to reference to deploy and export execution templates?

what is the expected behavior when a dir is references?
should the landscaper walk through the filesystem and template every file is finds?

**Comment by loewenstein** [comment]
@schrodit [Carvel YTT](https://github.com/vmware-tanzu/carvel-ytt) for example works on a directory. It still produces a single file if I remember correctly, but we'll have and want to pass a directory to the `ytt` binary.

**Comment by schrodit** [comment]
> @schrodit [Carvel YTT](https://github.com/vmware-tanzu/carvel-ytt) for example works on a directory. It still produces a single file if I remember correctly, but we'll have and want to pass a directory to the `ytt` binary.

the idea was that when new templating engines are implemented the structure of the [temaplte executor](https://github.com/gardener/landscaper/blob/master/apis/core/v1alpha1/types_blueprint.go#L129) is adjusted enhanced accordingly

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
