### ISSUE TITLE
Target Validation

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#141]
**How to categorize this issue?**

/area robustness
/kind epic
/priority 2

**What would you like to be added**:

Targets are input options for a blueprint and are heavily used in deploy items to describe the environment to deploy to.
Whereas default data imports are completely validated using the inline blueprint jsonschema definitions, targets are described by a type but the type configuration is not validated.

To improve the robustness of the service and to be able to also validate targets before even a blueprint is executed validation for target types is needed.

The validation should be done per target type and should validate the target config based on the specific type.
As target type are extensible we would need a way to describe target types.

Therefore 2 options are proposed:
1. using a similar system as kubernetes with its crd's (Target Resource Definition trd)
  - Pro: already known pattern, also types would be editable and viewable in the cluster
  - Con: another dependency that somehow needs to be pushed and maintained in the cluster. It is possible to have different trds in different systems for the same types.
2. target registry referenced by the component descriptor / blueprint
  - Pro: a blueprint developer can directly reference the definition for a target he wants to use. No duplicate tdr's for same types. Can be transported with the blueprint and other definitions
  - Con: yet another resource reference. system would be similar to the external jsonschema.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
