### ISSUE TITLE
Not able to access local oci chart with resolve

### ISSUE THREAD

**Issue by achimweigel** [gardener/landscaper#149]
**How to categorize this issue?**

/area TODO
/kind bug
/priority normal

**What happened**:

We want to access the bytes of a helm chart in a deployitem template with

```
{{ $resource := getResource .cd "name" "gardener-extension-provider-aws-chart" }}
chart: {{ resolve ( $resource.access ) | b64enc }}
```
 
If the helm chart is stored in the component descriptor oci artifact as a localOciBlob we get the following error:

```
'unable to template executions: template: execution:42:22: executing "execution" at <resolve ($resource.access)>: error calling resolve: unable to decode access to type ''localOciBlob'': unexpected end of JSON input'
```

**What you expected to happen**:

No error :-)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Landscaper version: 0.7.0
- Kubernetes version (use `kubectl version`):
- Others:

**Comment by schrodit** [comment]
Fixed with the upgrade of the component-spec
