### ISSUE TITLE
Installation import state

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#15]
It is currently hard to debug the templating and errors that occur in the running system.
The only way to inspect computed values that are used for templating is by debugging the landscaper.

This is not possible in a running system, therefore a resource is needed that shows current states and are easily accessible by a human operator.

The installation status field would be to much overhead for such a debugging.
Therefore, a possible solution would be to add a dedicated state resource that shows additional information for debug/observability purposes.

**Comment by In-Ko** [comment]
I believe this is a good starting point for the requested "better debugging support", as well as the "easy way to see the overall state of all deployments". Not sure about the title of the issue though ...

Such an improved debugging and state overview would also increase our work on the Gardener Components I guess.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
