### ISSUE TITLE
Deployer configs are not getting automatically converted

### ISSUE THREAD

**Issue by MrBatschner** [gardener/landscaper#155]
**How to categorize this issue?**

/area deployers
/kind bug
/priority 4

**What happened**:
The change introduced in PR #151 does not convert the deployer configs. If the manifest-deployer with the changes introduced in PR #154 is started with a _v1alpha1_ config, it will abort immediately with the error message `converting (v1alpha1.Configuration) to (v1alpha2.Configuration): unknown conversion`.

**What you expected to happen**:
`v1alpha.Configuration` gets successfully converted to `v1alpha2.Configuration` for the manifest-deployer (and all other deployers should they ever get another API version).

**How to reproduce it (as minimally and precisely as possible)**:
Use the manifest-deployer with the changes in PR #154 and start it with a `v1alpha.Configuration`.

**Anything else we need to know?**:

**Environment**
- Landscaper version: v0.8.0-dev, latest commit referenced in PR #154
- Kubernetes version (use `kubectl version`): 1.20.1

**Comment by schrodit** [comment]
fixed with https://github.com/gardener/landscaper/pull/151
