### ISSUE TITLE
Migration of Installations and DeployItems

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#16]
When developers start to build blueprints to install their software it will become necessary to migrate deploy items and or installations.

When a blueprint is updated the deployitem structure may change as multiple deploy items are aggregated together or a single deploy item is split into multiple ones.
The landscaper must support such scenarios as we do not want the be deleted and reinstalled afterwards (which would be the current behavior).

In addition, the same issue occurs when the structure of an aggregated blueprint changes and subinstallation and deployitems need to be migrated to their new structure.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
