### ISSUE TITLE
Enhance deletion operation

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#202]
**How to categorize this issue?**

/area robustness
/kind cleanup
/priority 3

The deletion flow of a installation can currently get stuck when the deploy item is once in a failed state.
It should be possible for the landscaper to self heal or retrigger reconcile using the `reconcile` operation.

**Comment by schrodit** [comment]
one part of this issue is to fix: https://github.com/gardener/landscaper/issues/230
here we should check if we have already installed anything.
If not the installation can be safely deleted

**Comment by Diaphteiros** [comment]
I noticed that it sometimes happens that all deploy items are gone, but the finalizer on the execution is not removed. So far I've seen this only in cases where installation, execution, and deploy item were in `Failed`.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
