### ISSUE TITLE
Extend conditional imports

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#210]
**How to categorize this issue?**

/area operations
/kind enhancement
/priority 3

**What would you like to be added**:
Currently, conditional imports can only use "is import given" as a condition and not check on the actual value. We should extend the concept to be able to compare the value of a specified import with a pre-defined value.

**Why is this needed**:
This is especially interesting since installations don't support optional exports, so the current implementation of conditional imports can only be used at top level. Having conditional imports which check for the value of the import would allow to import values depending on the exports of another installation.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
