### ISSUE TITLE
Optimize boolean flags in config

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#211]
**How to categorize this issue?**

/area TODO
/kind enhancement
/priority 4

**What would you like to be added**:
See https://github.com/gardener/landscaper/pull/185#discussion_r641541535 for context.

Having `disable` flags in the config is somewhat unintuitive, as setting them to `true` actually deactivates something instead of activating it. However, with golang defaulting booleans to `false`, changing the `disable` flag to an `enable` flag while keeping the current defaults requires pointers, as otherwise setting the flag to `false` and not setting it at all will be indistinguishable in the code.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
