### ISSUE TITLE
Enhance error messages for invalid landscaper config

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#220]
**How to categorize this issue?**

/area operations
/kind enhancement
/priority 4

**What would you like to be added**:
My landscaper pod is in crashloop backoff and this is the complete log:
```
yaml: line 13: mapping values are not allowed in this context%
```

I suspect that I somehow have invalid yaml in the config, but it would be nice if the error message would include this information.

I will update this issue with the root cause when I found it.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
