### ISSUE TITLE
Deployer Target Owner Object

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#246]
**How to categorize this issue?**

/area deployers
/kind enhancement
/priority 4

**Description**

Currently deployers identify their ownership for deployitem based on the target's labels and annotations.
This is could be hard to debug and is only configurable once per deployer.

To be able to also update the ownership during runtime and per namespace/target, a new possibility to configure the ownership during runtime with a user (operating) facing resource should be introduced.

The new object should be optional and should be added to the deployer lib as their can be a lot of reuse potential.

Subtasks:
- [ ] Add Generic `Owner` object crd. https://github.com/gardener/landscaper/pull/247
- [ ] Refactor CRD management as generic crd manager
- [ ] Implement owner reconcile in deployer lib

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
