### ISSUE TITLE
container deployer secret exceeds maximum name length of 63 characters

### ISSUE THREAD

**Issue by reshnm** [gardener/landscaper#296]
**How to categorize this issue?**

/area container-deployer
/kind bug
/priority 3

**What happened**:

Apparently pod volume names have a [maximum length of 63 characters](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/): 

```
Warning  CreatePod  25s   container.deployer.landscaper.gardener.cloud  Pod "virtual-garden-gx7nk-virtual-garden-container-deployer-gr986tkb" is invalid: [spec.volumes[4].name: Invalid value: "default-virtual-garden-gx7nk-virtual-garden-container-deployer-gr9nr-cdpullsec": must be no more than 63 characters, spec.initContainers[0].volumeMounts[3].name: Not found: "default-virtual-garden-gx7nk-virtual-garden-container-deployer-gr9nr-cdpullsec"]
```

It must be ensured, that this limit is not exceeded.

**What you expected to happen**:

Regardless of the length of the installation name, the Kubernetes object name limits must be respected.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Landscaper version: 0.11.0
- Kubernetes version (use `kubectl version`): N/A
- Others:

**Comment by schrodit** [comment]
The error message indicate that the issue is not the length of the secret name but rather the name length of the volume mount name which is the same as the secret name currently.

Although we could in the future also exceed the secret name limit. But lets see if this will be actually an issue
