### ISSUE TITLE
landscaper resources can't be deleted

### ISSUE THREAD

**Issue by reshnm** [gardener/landscaper#309]
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:

There are several situations that will lead to landscaper resources that can't be deleted anymore.
This list aims to collect situations/constellation which lead to non-deletable landscaper resources (installations, executions, deployitems).

- Installation references a non-existing component descriptor. The installation will fail and can't be delete afterwards.
- A Helm deployment contains a namespace. In some instances the helm deployment can't be deleted anymore.
  This could possibly also happen with other resources.
```
{"level":"error","ts":"2021-09-09T08:50:58.140Z","logger":"setup.deployer.HelmDeployer.controller.deployitem","msg":"Reconciler error","reconciler group":"landscaper.gardener.cloud","reconciler kind":"DeployItem","name":"landscaper-rbac-pg5sr","namespace":"default","error":"waiting for the deletion of \"ls-system/ls-system(Namespace)\" to be completed"}
```
- A subinstallation imports a target that is created by a different subinstallation. It seems that the dependeny detection is not correctly working for target imports. This leads to a situation where both subinstallations are executed simultaneously and result in an error. Deleting the installation fails afterwards.
- When the target for a deployitem is no longer reachable/accessible, the deployitem can't be deleted and will be stuck. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Landscaper version: 0.12.0
- Kubernetes version (use `kubectl version`): N/A
- Others:

**Comment by schrodit** [comment]
> Installation references a non-existing component descriptor. The installation will fail and can't be delete afterwards.

this likely is the same category of issues as https://github.com/gardener/landscaper/issues/230

**Comment by In-Ko** [comment]
- Installation references a non-existing component descriptor. The installation will fail and can't be delete afterwards.
  - Deletion fixed. 
 
- A Helm deployment contains a namespace. In some instances the helm deployment can't be deleted anymore.
  This could possibly also happen with other resources.
```
{"level":"error","ts":"2021-09-09T08:50:58.140Z","logger":"setup.deployer.HelmDeployer.controller.deployitem","msg":"Reconciler error","reconciler group":"landscaper.gardener.cloud","reconciler kind":"DeployItem","name":"landscaper-rbac-pg5sr","namespace":"default","error":"waiting for the deletion of \"ls-system/ls-system(Namespace)\" to be completed"}
```
  - Fixed.
 
- A subinstallation imports a target that is created by a different subinstallation. It seems that the dependeny detection is not correctly working for target imports. This leads to a situation where both subinstallations are executed simultaneously and result in an error. Deleting the installation fails afterwards.
  - Fixed.

- When the target for a deployitem is no longer reachable/accessible, the deployitem can't be deleted and will be stuck. 
  - Still open, but this is not easy, e.g. if the cluster is not reachable...

**Comment by achimweigel** [comment]
Open:

- When the target for a deploy item is no longer reachable/accessible, the deploy item can't be deleted and will be stuck. 
  - Still open, but this is not easy, e.g. if the cluster is not reachable...
  - We should at least provide a simple solution for some cleanup. Thereby we should consider that it is not only about the complete deletion of an installation with one deploy item but also about installations with sub-installations and many deploy items. Thereby the deletion of the root installation must be considered as well as the deletion of only some deploy items. 
  - Two possible solutions:
    - If the root installation gets a force-delete annotation, this is propagated to all deploy items and every deploy item where the deletion has failed is deleted without deleting the resources on the target cluster. Afterwards the force-delete annotations must have been removed from all landscaper resources belonging to the root installation.
    - We just add a simple command to the landscaper-cli just to delete all relevant deploy items with respect to a root installation without triggering some deinstallation on the target cluster. We must check if the current landscaper implementation continues afterwards the processing of the root installation and should come to a success state if no other problems occurs.

**Comment by In-Ko** [comment]
Closing this, as a similar issue is now on the bew backlog project.
