### ISSUE TITLE
Provide local blueprint and aggregated blueprint validation and visualization tooling

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#320]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 4

**What would you like to be added**:

With bigger aggregated blueprints its hard to see the import export dependencies and hard to validate these bleuprints.

We should provide a clientside tooling to validate blueprints and also visualize.

Implementation:

For analyzing and validating we should provide a graph of all dependencies. (in the landscaper)

The landscaper-cli should call the validation and be able to use dot syntax to visualize that graph.
- interesting references how pprof is doing the visualization
  - https://github.com/google/pprof/blob/01bbb1931b22f146c60e458c0d3fb88e97fc581d/internal/driver/webui.go#L332

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
