### ISSUE TITLE
Support Data flow between subinstallations and deployitems in one chart

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#345]
**How to categorize this issue?**

/kind enhancement
/priority 4

**What would you like to be added**:

Currently a blueprint can define deployitems and subinstallations that can be used independently and are executed in parallel.
But in most use cases either deploy item *OR* subinstallations are used because there is no real benefit or way for reusability.
In most reuse scenario, data is calculated by subinstallations and imported by deployitems or deployitems export data and imported by installations.
![image](https://user-images.githubusercontent.com/7979201/137899873-f06c92b1-d29d-40ae-b5f4-a93fd9317ce3.png)
![image](https://user-images.githubusercontent.com/7979201/137900056-cdd2da70-762f-4a6f-8e30-881aa1e1b2a1.png)

This scenario is currently only possible with 2 blueprint which adds some overhead and makes blueprints hard to consume.
So to encourage reusability we should make it easier to consume other blueprints in one blueprint.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
