### ISSUE TITLE
Script/Golang Deployer

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#346]
**How to categorize this issue?**

/area deployers
/kind enhancement
/priority 4

**What would you like to be added**:

Some scenarios (image vector overwrite, machine image calucation) currently require blueprints that calculates some data with more logic than templates can offer.
To support reusability one way is to offer such functionality as blueprint build with a container deployer.
*BUT* using a container deployer has lot of overhead for development testing and execution which is most of the time unnecessary.

Therefore, we should offer an easy and lightweight possibility to run code in a deployer.
Maybe only support for golang (or a binary) is enough for now.

Requirements:
- make it possible to easily run code
- security (network, filesystem access, memory, cpu, etc..)

**Comment by In-Ko** [comment]
- Decision is that the Script/Golang Deployer is nice-2-have, but the Container-Deployer is much more secure and does not have so much overhead.
- Moving to "To Do", maybe pick this up at a later point in time

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
