### ISSUE TITLE
General Jsonschema component

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#349]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement
/priority 3

**What would you like to be added**:

When creating blueprints an essential part is specifying exact jsonschema's so that the format can be validated and people know the interface.
In the gardener/kubernetes case there are a lot of similar jsonschema can are used across components/schema.
This includes `resource-requirements`, `aws-credentials`, etc. .

We should have a component that includes such general jsonschemas so that it can be reused by other components and we do not have redefine these with every new component.

**Comment by danielfoehrKn** [comment]
While this is certainly a possible approach, at least for golang-based project, I prefer a completely generated blueprint + JSON schema approach. 
Reasons are
- no manual maintenance in case the import configuration changes (add a field in my import configuration, I upgrade a dependency)
- automatic detection if the blueprint JSONSchema is out-of-sync with the import configuration (via `make` scripts executed during CI runs).
- Kubernetes types are almost all configured to expose correct JSONSchema 
- Tooling support is available via `openapi-gen` used internally by Kubernetes and Gardener

The problems with pre-defined types are
- why would I use a pre-defined type if I can just generate it based on my import configuration? It will increase the size of the blueprint a bit (more characters essential), but not by much.
- Effort to maintain shared predefined types
- Coding effort in the landscaper itself to recognize pre-defined types

I opened a [PR with a working generator for blueprints](https://github.com/gardener/gardener/pull/5233).

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
