### ISSUE TITLE
Container Deployer does not delete service accounts

### ISSUE THREAD

**Issue by achimweigel** [gardener/landscaper#353]
**How to categorize this issue?**

/area container-deployer
/kind bug
/priority 3

**What happened**:

The container deployer does not delete the service accounts used for init and wait container of particular container deployments. The same is true for role bindings and pods created by the container deployer. 

An example of this situation could be seen in the namespace ls-system of the landscaper installation in landscape-dev-garden of the public environment. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Landscaper version:
- Kubernetes version (use `kubectl version`):
- Others:

**Comment by schrodit** [comment]
Not sure but could be the expected behavior.
Can you check if the corresponding deploy items are also deleted?
Because these resources are currently only deleted if the deploy item is delete, otherwise we would regenerate the same resources with every reconcile.

**Comment by achimweigel** [comment]
Sorry, I forgot to close this issue. I checked the coding and it looked ok. I found out that the deploy items where deleted manually and this is the reason for this.

**Comment by schrodit** [comment]
> Sorry, I forgot to close this issue. I checked the coding and it looked ok. I found out that the deploy items where deleted manually and this is the reason for this.

ah ok so you mean that the finalizer has been manually removed.
Ok then we should rather implement something as described here: https://github.com/gardener/landscaper/issues/120

**Comment by In-Ko** [comment]
So this issue can / will be closed, as the observed behaviour is as intended ? If so, please go ahead and close.
