### ISSUE TITLE
Provide Scaffolding-Project to simplify creation of new Landscaper-Components

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscaper#359]
**How to categorize this issue?**
/kind enhancement
/priority 2

**What would you like to be added**:
We need to provide a scaffolding project ("template project"), which others can use in order to start implementing a new component with the Landscaper. This project should contain everything needed for a jump-start.

**Why is this needed**:
Based on Feedback, we see the need to simplify the initial steps needed to create a new landscaper component. A first step in this direction is the creation of a project, which can be copied and used as an initial skeleton.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
