### ISSUE TITLE
Improve reconcile in case of a landscaper upgrade

### ISSUE THREAD

**Issue by achimweigel** [gardener/landscaper#380]
**How to categorize this issue?**

/area deployers
/kind bug
/priority 3

**What happened**:

Several installations failed due to an error of the landscaper. After the upgrade of the landscaper the failed installations were not reconciled and therefore remain in that state. This affected also the installations for the configured deployer.

The situation became even more complicated in case an agent is running. The installations for the deployer under the control of the agent were updated first but failed du to the bug in the agent. Then the agent was updated but its deployer were not reconciled again. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Landscaper version:
- Kubernetes version (use `kubectl version`):
- Others:

**Comment by In-Ko** [comment]
Closing this, as it has been moved to the new backlog project.
