### ISSUE TITLE
Clear names for exports

### ISSUE THREAD

**Issue by achimweigel** [gardener/landscaper#390]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 3

**What would you like to be added**:

For import data it is possible to reference them by their real name and not a hash using the notation "#name". The same should be possible for export data.

**Why is this needed**:

**Comment by In-Ko** [comment]
#-notation has been switched off in the meantime also for imports, so this does not make much sense anymore.
@Diaphteiros : Please add the respective PR.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
