### ISSUE TITLE
Support "StopReconcile" Annotation (was "Explicit reconcile order for root installations")

### ISSUE THREAD

**Issue by achimweigel** [gardener/landscaper#399]
**How to categorize this issue?**

/area deployers
/kind enhancement
/priority 3

**What would you like to be added**:

Assume you have several to root installations, e.g. I1, I2, I3 where I3 import data from I2 and I2 from I1. Now you want to upgrade the version of the referenced Component Descriptor / Blueprint in I1 and I3. Thereby it is critical, that the upgrade of I1 is executed before I3. With the current solution this is not possible and the client must coordinate the upgrade order for the installations. 

To get more control of the upgrade/reconcile order a mechanism is needed to stop the reconcile of a set of root installations, upgrade some of them and then start the reconcile of all these installations in a predefined order. 

This feature was requested by the Gardener team for the deployment of Gardener with Landscaper. 
 
**Why is this needed**:

**Comment by In-Ko** [comment]
This is exactly what we discussed this morning (FYI @Diaphteiros). We should have a "SkipReconcile" Annotation, which would lead to Landscaper Controller not reconciling anymore, until this annotation is deleted again from all relevant installations. This has prio now.
