### ISSUE TITLE
Make installations independent from component descriptors

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#402]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 5

**What would you like to be added**:
Currently, each installation requires a CD (although we support an 'inline' case for development purposes). This hard requirement is not necessary by the concept, so we should make the CD in an installation optional.

There are further points to be adapted for this to work: blueprints can currently only be provided 'inline' or by referencing a resource from the CD. So we need further options for installations without CD.

Two ideas:
- Referencing blueprints in an OCI registry. This should not be difficult, since blueprints may be stored in an OCI registry already and fetching them from there shouldn't be a problem.
- Introducing a CRD which allows putting blueprints into a k8s cluster. This is a little more difficult. A blueprint might already look like a k8s resource, but we would need to find a solution for the corresponding filesystem. Easiest solution is probably to not make the blueprint itself a k8s resource, but wrap it in a bigger construct which also contains/references the filesystem. Another problem is that while artifacts in an OCI registry are usually not overwritten or deleted, this can happen way easier with a k8s resource and we would have to find a way prevent or handle it.

**Comment**:
While there is no necessity for an installation to be linked to a CD in the concept, the current implementation heavily relies on the CD and lots of refactoring will be required to remove this requirement.

Proposed by @mandelsoft

**Comment by In-Ko** [comment]
Closing, as this has been moved to the new project backlog.
