### ISSUE TITLE
Remove limitation of blueprint OCI artifacts to one layer

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#403]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 5

**What would you like to be added**:
Blueprint OCI artifacts are currently limited to only one layer (see [here](https://github.com/gardener/landscaper/blob/master/docs/usage/Blueprints.md#oci)). This limitation should either be explained in the documentation or, if it is not necessary, removed.

Proposed by @mandelsoft

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
