### ISSUE TITLE
Add generic 'container' executor as templating option

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#404]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 5

**What would you like to be added**:
Currently, only spiff and go-template are supported as templating engine options for rendering deployitem or export templates. There are cases, however, in which plain templating is not enough or just not desired. To solve this, we should add a third option which allows executing arbitrary code to generate the required values.

Proposed by @mandelsoft

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
