### ISSUE TITLE
Manual changes to an execution are not reverted

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#408]
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:
I created an installation, which has a subinstallation, which creates an execution with one deployitem. Then I modified the execution manually and made a change to the deployitem template. Landscaper did not revert the change done to the execution. This could only be enforced by using a force-reconcile annotation on the subinstallation.

**What you expected to happen**:
I would expect that landscaper automatically recognizes changes to executions and reverts them.
Even if it doesn't, this should at least happen with a reconcile Annotation on the root installation, but not only did that one not help, but even a force-reconcile annotation on the root installation did not enforce recreation of the execution.
A force-reconcile annotation on the subinstallation helped, but a user should not have to search for the correct subinstallation, after he accidentally messed up an execution.

**Anything else we need to know?**:
Some proposals how we could solve this:
1. Landscaper automatically recognizes changes to executions and reverts them, as it does with deployitems. This would be the 'nicest' solution, but it might require additional status fields and logic to detect changes.
2. Landscaper does not revert changed executions on its own, but force-reconcile annotations on installations are at least propagated to all of their subinstallations, so that a force-reconcile annotation on the root installation will re-create the execution and overwrite any changes.

**Comment by Diaphteiros** [comment]
cc @achimweigel @robertgraeff @reshnm

**Comment by In-Ko** [comment]
Moved to new backlog project, therefore closing this here.
