### ISSUE TITLE
Take dependencies into account when updating subinstallations

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#409]
**How to categorize this issue?**

/area robustness
/kind bug
/priority 2

**The Problem**:
Currently, the landscaper applies subinstallations one after the other, in the order in which they are specified in the blueprint. This can cause problems: Imagine two subinstallations, A and B, where B depends on A. Unfortunately, they are given in the wrong order in the aggregated blueprint - first B, then A. During an update, it could happen that the new version of B (B2) will be pushed into the cluster *and* picked up by the landscaper before the manifest for A2 has been pushed into the cluster. The result would be that the landscaper checks B2's dependencies, but since A has not been updated yet, everything looks up-to-date and the landscaper will start processing B2. If B2 now depends on any changes or migrations implemented in A2, this will fail and might even leave the deployed product in an inconsistent state.

The solution is to construct the dependency graph of the subinstallations and update them according to that, this way it could never happen that a new version of a depending component is picked by the landscaper before the new version of the component it depends on has been pushed into the cluster.
The landscaper knows the import/export flow between subinstallations and therefore is able to compute this dependency tree.

**Comment by Diaphteiros** [comment]
cc @reshnm @achimweigel @robertgraeff

**Comment by In-Ko** [comment]
This is the issue we discussed this morning (Aggregated blueprints not sticking to the right sequence), right ? So this has priority now.
