### ISSUE TITLE
Enhance the aggregated blueprint tutorial

### ISSUE THREAD

**Issue by reshnm** [gardener/landscaper#417]
**How to categorize this issue?**

/area documentation
/kind enhancement
/priority 2

**What would you like to be added**:

The aggregated blueprint tutorial should contain a more complex (and probably more real use-case) scenario.
This should also show hot to use templating with import data mapping etc.
Show how the use case can be implented via the aggregated blueprint feature or via single installations using the "block reconcile annotation".

**Why is this needed**:

Give the user a guideline how to use the landscaper in more complex deployments that is inspired by real use-case scenarios.
The tutorial ressources can be used in integration testing and verify that the landscaper is working as expected with complex deployment scenarios.

**Comment by In-Ko** [comment]
moved to other backlog project

**Comment by In-Ko** [comment]
Closing, since this is moved to the new backlog.
