### ISSUE TITLE
dynamically update exports

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#420]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 5

**What would you like to be added**:
Currently, exports are only generated after the deployitem has run. There are some cases, however, where it is desirable to update the exports of a deployitem without processing it again.
An example would be the helm deployer: it allows exporting fields from generated manifests. This not only applies to the generated values, but it can also export fields which are added to an applied resource later on, for example loadbalancer IPs in service objects. If now the loadbalancer IP changes and the service object is updated somehow, it should be possible to reflect this change in the deployitem's exports and this should happen automatically. There is also no need to run the deployitem again, as the generated manifests didn't change.

There are multiple requirements for this:
1. The corresponding deployers need to be able to watch all created resources and react to changes by updating the deployitems exports.
2. The landscaper needs to react to deployitem export changes which occur independently of a deployitem processing and it has to properly propagate the new exports to the installation.

While it would be nice to have this functionality, it is not trivial to implement. Landscaper currently only expects exports to change when the creating resources are `Progressing` and this approach would - at least partly - break with this assumption.

**Comment by In-Ko** [comment]
moved to new project board.

**Comment by In-Ko** [comment]
Closing, since this is moved to the new backlog.
