### ISSUE TITLE
enable targetlist exports

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#421]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 5

**What would you like to be added**:
It is possible to import an arbitrary number of targets via a 'targetlist' import. There are also cases where it would be desirable to export an arbitrary amount of targets, e.g. for a component which creates X k8s clusters, where X is an imported value. As there are no targetlist exports, it is currently not possible to export multiple targets unless the exact amount is known at build time.

**Comment by In-Ko** [comment]
Moved to new project backlog.
