### ISSUE TITLE
secretRefs/configMapRefs in installation imports can access any namespace

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#422]
**How to categorize this issue?**

/area security
/kind bug
/priority 3

**What happened**:
Installations can currently access any secret or configmap via their `secretRef` and `configMapRef` fields in the imports. This violates any namespace-based access control and should not be possible.

The quick solution would be to restrict access to secrets/configmaps in the installation's namespace.
The better solution would be to have some kind of access control mechanism which can be used to allow access to specific resources in specific namespaces, see #423.

**Comment by In-Ko** [comment]
As discussed: Let's make it configurable, whether the namespace restrictions should through an error, or not. This has to be configurable per landscaper (and also per landscaper-as-a-service instance).

**Comment by In-Ko** [comment]
Moved to new project backlog.

**Comment by In-Ko** [comment]
Closing, since this is moved to the new backlog.
