### ISSUE TITLE
access control for cross-namespace consumption of resources

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#423]
**How to categorize this issue?**

/area security
/area usability
/kind enhancement
/priority 5

**What would you like to be added**:
It should be possible to reference secrets and configmaps in another namespace than the one the accessing installation is in. However, this needs to be done in a controlled manner. A possible solution would be some kind of 'access permission objects' which reside in the cluster and grant access to resources in a certain namespace. The object resides in the accessed namespace itself, so it can only be created by someone who already has access to that namespace, and it specifies from which resources/namespaces access to which resources in its own namespace should be possible.

**Comment by reshnm** [comment]
I would like to extend this enhancement to Landscaper Targets.

**Comment by Diaphteiros** [comment]
> I would like to extend this enhancement to Landscaper Targets.

Yes, that was bad phrasing from me, it was intended to use this mechanic for all kinds of references, including targets.

**Comment by In-Ko** [comment]
This is not super critical anymore, if we go for the solution as proposed in #422 .

**Comment by In-Ko** [comment]
Moved to new project backlog.

**Comment by In-Ko** [comment]
Closing, since this is moved to the new backlog.
