### ISSUE TITLE
CD imports should be able to reference CDs from the owning CD's reference list

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#424]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 5

**What would you like to be added**:
There is a special import type for component descriptor imports. The installation can reference CDs using an OCI access URI or using a secret/configmap reference (latter one is meant for development purposes only). The most intuitive option - referencing a component descriptor which is in the list of 'referenced component descriptors' of the owning component's descriptor - is missing though.

**Comment by In-Ko** [comment]
We will not invest here, as this is all possible using blueprints (and this is how it should be done).
Let's discuss, whether we can remove the CD type as import to avoid further complexity for stakeholders.

**Comment by In-Ko** [comment]
Moved to new project backlog (with different title, as it's more about whether we can safely remove the "CD Type" from supported import types or not).

**Comment by In-Ko** [comment]
Closing, since it has been moved to the new backlog.
