### ISSUE TITLE
use templating execution for importDataMappings/exportDataMappings

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#425]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 3

**What would you like to be added**:
Opposed to any other templating in the landscaper context, importDataMappings and exportDataMappings have a different structure and only allow the spiff template engine. The reason for this was that spiff templates are still valid YAML and both mentioned templates are part of an installation - and therefore part of a k8s resource - while all other templates reside within the blueprint. Technically, there should be no problem with other templating languages if the template is provided as an inline text value.
Both mentioned fields should be adapted to look and work like the templates in the blueprint. This is not only more intuitive, but it also frees users from the need to learn and use the unknown spiff templating language.

**Comment by In-Ko** [comment]
- should be done soon, as
  - this is the only place where we ONLY have spiff (and we should have go-templating also here, as in blueprint templating)
  - reduces complexity (which is often criticised)

**Comment by In-Ko** [comment]
Moved to new project backlog.

**Comment by In-Ko** [comment]
Closing, since it has been moved to the new backlog.
