### ISSUE TITLE
cache generated imports

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#426]
**How to categorize this issue?**

/area performance
/kind enhancement
/priority 4

**What would you like to be added**:
Currently, the installation imports are rendered each time the installation is processed. There might be several disadvantages of this approach in the future:
- if we allow a 'container executor' for template rendering (see #427), rendering the imports is potentially expensive and we don't want to do it more often than necessary
- if we want to make the import values available to the export rendering - which we want to do for consistency (use the same template bindings for all templating steps) - we would need to render them again for the export generation, as this is done in a separate reconciliation where we don't have access to the previously rendered import values

To solve this, an installation should 'cache' the rendered imports and only render them again if any of the imported dataobjects/targets changed. Unfortunately, this caching has to happen in a k8s resource.
The data could be stored in a dataobject resource with a specific name. With optional fragmentation into multiple objects, should the rendered imports ever become too big for the etcd storage limit (it's about 5MB for a single k8s resource, if I remember correctly ...), but we probably don't need that for the first version.

**Comment by In-Ko** [comment]
- let's first get the exportDataMapping working on the main branch (Uwe might already have something for that)
- After this, this issue makes sense, especially for direct import to export data transfer

**Comment by In-Ko** [comment]
Moved to new project backlog

**Comment by In-Ko** [comment]
Closing, since it has been moved to the new backlog.
