### ISSUE TITLE
add 'generic' template executor

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#427]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 5

**What would you like to be added**:
We currently allow spiff and go-template for rendering templates in the Landscaper context. There might be users who don't want to use any of these, or even can't because their templating is too complex to be described in these languages. We should have an option to use arbitrary code for rendering templates, e.g. in form of a container which is executed in a pod.

**Comment by In-Ko** [comment]
Moved to new project backlog.

**Comment by In-Ko** [comment]
Closing, since it has been moved to the new backlog.
