### ISSUE TITLE
Landscaper Tutorial broken probably due to outdated nginx version

### ISSUE THREAD

**Issue by jkafka23** [gardener/landscaper#428]
**How to categorize this issue?**

/kind bug
/priority 3

**What happened**:
This landscaper tutorial https://github.com/gardener/landscaper/blob/master/docs/level_0/first_example_installation.md 
is broken. Deployment of nginx controller fails with one or more of these error messages:

"
E0224 15:23:12.827553       8 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 15:23:13.993874       8 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 15:23:16.142025       8 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 15:23:19.769150       8 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 15:23:29.515845       8 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 15:23:44.446949       8 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
"

**How to reproduce it (as minimally and precisely as possible)**:
Run the above tutorial on any cluster.

**Anything else we need to know?**:
The root cause of the error seems to be known and is described here:
https://github.com/bitnami/charts/issues/7264

- Landscaper version: eu.gcr.io/gardener-project/landscaper/landscaper-controller:v0.17.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
- Others:

**Comment by Diaphteiros** [comment]
If I remember correctly, k8s changed the Ingress apiversion. It was `extensions/v1beta1` before and is now `networking.k8s.io/v1`. So this bug could actually depend on the k8s version of the cluster where you run the test on, which is why we didn't notice it earlier.
