### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by kramerul** [gardener/landscaper#65]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority normal

**What would you like to be added**:

I would like to see a dependency management with the following features
* Specify dependencies between blueprints (e.g cf-for-k8s depends on istio)
* Specify versions ranges for the dependency (e.g cf-for-k8s requires istio with a version greater than 1.7)
* If I install one blueprint, which depends on another, the missing blueprint is automatically installed
* One blueprint should be able to read installation values from a dependent blueprint (e.g. cf-for-k8s needs to get the credentials for an already installed docker registry, which was installed before, triggered by the kyma installation). It would be even better, if cf-for-k8s could trigger the creation of new credentials.
* I'm not sure if there should be some kind of reference counting (istio should remain in the cluster, if cf-for-k8s is uninstalled but kyma is still installed).

If these features already exist, it would be nice to have a detailed description, how this works.

**Why is this needed**:

The motivation can be found [here](https://github.com/gardener/landscaper/issues/60#issuecomment-737029632)

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
