### ISSUE TITLE
Deleting cycle of installations

### ISSUE THREAD

**Issue by robertgraeff** [gardener/landscaper#70]
**How to categorize this issue?**
/kind bug
/priority normal

**What happened**:
We have two installations which depend on each other. Each of them imports an export parameter of the other. The installations are in phase PendingDependencies for some time and switch then to phase Failed ("unable to get data object..."). Then we try to delete both installations, but the installations remain there.

**What you expected to happen**:
It should be possible to delete the installations.

**Comment by Diaphteiros** [comment]
Ah, I always wanted to say that: It's not a bug, it's a feature! 
As @schrodit mentioned [here](https://github.com/gardener/landscaper/issues/60#issuecomment-738642452), an installation that is depended on by another installation cannot be deleted. 
The problem that you saw probably also comes from the cyclic dependency - both installations are waiting for the other installation to finish before updating themselves ... which will never happen. 

I think we don't support cyclic dependencies between installations in general. @schrodit correct me, if I'm wrong.

**Comment by Haegi** [comment]
We are facing a similar problem. If one helm deployItem out of four fails, we are not able to delete the installation.
Only the successful deployItems get deleted.

After the installation:
```
NAME                                                                    TYPE                                            PHASE       EXPORTREF   AGE
deployitem.landscaper.gardener.cloud/c21s-control-prerequisites-5t2qf   landscaper.gardener.cloud/helm                  Succeeded               35s
deployitem.landscaper.gardener.cloud/c21s-controller-q4sxq              landscaper.gardener.cloud/helm                                          35s
deployitem.landscaper.gardener.cloud/c21s-crds-6hdzx                    landscaper.gardener.cloud/helm                  Succeeded               35s
deployitem.landscaper.gardener.cloud/c21s-create-namespace-kj74g        landscaper.gardener.cloud/kubernetes-manifest   Succeeded               35s

NAME                                       PHASE         EXPORTREF   AGE
execution.landscaper.gardener.cloud/c21s   Progressing               35s

NAME                                          PHASE         CONFIGGEN   EXECUTION   AGE
installation.landscaper.gardener.cloud/c21s   Progressing               c21s        42s
```

After the deletion of the installation:
```
NAME                                                         TYPE                             PHASE   EXPORTREF   AGE
deployitem.landscaper.gardener.cloud/c21s-controller-q4sxq   landscaper.gardener.cloud/helm                       4m19s

NAME                                       PHASE      EXPORTREF   AGE
execution.landscaper.gardener.cloud/c21s   Deleting               4m19s

NAME                                          PHASE      CONFIGGEN   EXECUTION   AGE
installation.landscaper.gardener.cloud/c21s   Deleting               c21s        4m26s
```

**Comment by In-Ko** [comment]
I agree with the cyclic dependencies (as mentioned in this [comment](https://github.com/gardener/landscaper/issues/70#issuecomment-741760670)), so we should not allow those.
- Wouldn't a suitable follow-up be that we check for cyclic dependencies during designtime, so that the error not being able to delete installations if there is a cyclic dependency will never happen again ?

What about the second issue in this task ? If one Helm deployItem out of 4 fails, the whole installation can not be deleted ? I feel that we can (and have to) improve our tools here.

**Comment by schrodit** [comment]
> I agree with the cyclic dependencies (as mentioned in this comment), so we should not allow those.
>
> Wouldn't a suitable follow-up be that we check for cyclic dependencies during designtime, so that the error not being able to delete installations if there is a cyclic dependency will never happen again ?

yes we are able to determine cyclic dependencies and should directly fail the aggregated installation or all involved root installations.

> What about the second issue in this task ? If one Helm deployItem out of 4 fails, the whole installation can not be deleted ? I feel that we can (and have to) improve our tools here.

not sure why we are unable to delete it. but it should be possible to delete a failed helm deploy item.
Are there steps to reproduce the issue (because I currently do not see why it shouldn't work)?

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
