### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by kramerul** [gardener/landscaper#75]
**How to categorize this issue?**

/area documentation
/kind bug
/priority normal

**What happened**:

The component descriptor in  https://github.com/gardener/landscaper/blob/master/docs/tutorials/01-create-simple-blueprint.md doesn't contain a `repositoryContexts`. The deployment is not working.

**What you expected to happen**:

Documentation is correct

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

**Environment**:

- Landscaper version:
- Kubernetes version (use `kubectl version`):
- Others:

**Comment by schrodit** [comment]
Only the first component descriptor that just includes the helm chart does not contain a repository context.
The idea here was that the first component descriptor is not finished yet (the blueprint is still missing).
So no unfinished component descriptor is uploaded.

The complete component descriptor is defined in the upload section which then also contains the repository context. 
See https://github.com/gardener/landscaper/blob/master/docs/tutorials/01-create-simple-blueprint.md#remote-upload

There is also a note that says that the repository context and the blueprint have to be added:

![image](https://user-images.githubusercontent.com/7979201/102323690-1de7e580-3f81-11eb-886d-6e707c8ddfd9.png)

Maybe we should make that explanation more prominent.
e.g. ⚠️ Note that the repository context as well as the blueprint resource should be added to the component descriptor
