### ISSUE TITLE
Installation of chart with subcharts is not handled as expected

### ISSUE THREAD

**Issue by Goshoy** [gardener/landscaper#774]
**How to categorize this issue?**

/area helm-deployer
/kind bug
/priority 3

**What happened**:
When installing a chart which has subcharts the landscaper manages to install the main chart successfully, however when the subchart is "disabled" (it should not be installed) it looks like it still tries to render/create (from helm perspective) the resources of the subchart.

**What you expected to happen**:
I expected only the main chart to be installed and the subchart to not be involved at all.

**How to reproduce it (as minimally and precisely as possible)**:
I have not tried to reproduce the issue with different helm chart from the one of Connectivity Service. It would be hard to navigate you how to install our chart and it would require subaccounts in CF and so on. I am available to help reproduce the issue at any time. Also I can leave a failed installation in the landscaper instance if needed for troubleshooting. Or I guess you could update the installation resource I used and reproduce it.

I am attaching the chart which I am trying to install. 
[connectivity-proxy-k8s-helm-2.9.0.tgz](https://github.com/gardener/landscaper/files/11964943/connectivity-proxy-k8s-helm-2.9.0.tgz)

**Anything else we need to know?**:
If I try to install the chart with the subchart enabled it works fine.

**Environment**:

- Landscaper version: v0.40.0
- Kubernetes version (use `kubectl version`): v1.25
- Others:

**Comment by robertgraeff** [comment]
We can now reproduce this issue and are working on a fix.

The actual helm install does indeed skip the disabled sub chart (as desired). But the readiness check afterwards does not ignore them. Therefore, the readiness check waits for a deployment to become ready which has not been deployed. This causes the error.

**Comment by Goshoy** [comment]
Nice to hear! Thank you!

**Comment by robertgraeff** [comment]
@Goshoy 
Hi Georgi, 

the fix for this issue has now been deployed n the Landscaper CANARY landscape.

Best regards,
Robert
