### ISSUE TITLE
DeployItems keep being reconciled for more than 6 months

### ISSUE THREAD

**Issue by morri-son** [gardener/landscaper#875]
/area helm-deployer
/bug bug|
/priority 3 

**What happened**:
In the logging stack for LIVE there's a repeating issue with the reconciliation of all three deploy items of an installation, e.g. https://dashboards-sf-4b9f9729-2334-43cb-aa27-aa72888cf7b2.cls-01.cloud.logs.services.eu10.hana.ondemand.com/app/dashboards#/view/271d3fc0-f86f-11ed-97fa-61b53b28387e?_g=h@6dc552e&_a=h@731558efor

It is for tenant id k5f74a4p in resource cluster t-k5f74a4p/dev-landscaper-685gz, namespace cu-landscaper-resources-cf-us10-staging. The installation is "ingress-gateway-installation". Its three deployItems and the installation are all succeeded in April 2023, but the Helm deployer in the target landscaper keeps reconciling the DeployItems and fails with 

```
{"level":"error","ts":"2023-10-31T13:12:30.659Z","logger":"deployer.helm","msg":"unable to get landscaper context: contexts.landscaper.gardener.cloud \"context\" not found","reconciledResourceKind":"DeployItem","deployItemType":"landscaper.gardener.cloud/helm","reconcileID":"5c3e7fda-0fd7-4163-8814-74c1409b3fe3","reconciledResource":"cu-landscaper-resources-cf-us10-staging/ingress-gateway-installation-istio-base-mtm79","method":"LogErrorAndGetReconcileResult","error":"unable to get landscaper context: contexts.landscaper.gardener.cloud \"context\" not found"}
```

as the installation refers to a context that has been deleted in the meantime

**What you expected to happen**:
The Installation / DeployItems should be updated to "failed", so that the HelmDeployer stops reconciling.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
LIVE

- Landscaper version: v0.79.0
- Kubernetes version (use `kubectl version`): v1.25.12

**Comment by achimweigel** [comment]
Fixed with PR https://github.com/gardener/landscaper/pull/877
