### ISSUE TITLE
New Documentation structure

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#96]
**How to categorize this issue?**

/area documentation
/kind enhancement
/priority normal

Umbrella issue for the new documentation structure.

The new documentation structure consists of different levels of knowledge which should represent the learning path.
And also should represent the different personas and their prerequisites to get started.

- [ ] First task is to adapt the documentation to match the new levels.

### Motivation

- [x] what is Landscaper, why do I need it, what does it
- [x] first simple example
  - install Landscaper helm chart
  - nginx example

### Level 0 (Beginner)

- [ ] how can I install Landscaper (landscaper-cli init)
  - landscaper configuration (credentials)
  - Deployer
- [ ] what components does Landscaper consists of
  - their relationship
  - only user facing components (Blueprint, Component Descriptor installation, target/dataobject, deploy item)
  - were do the components live (compare to containers)
- [ ] Blueprint 
  - only parts: imports, exports
- [ ] Installations
  - find issues
  - Provide configuration (data)
  - create initial installation

#### Landscaper Operator

- [ ] how can I install the landscaper (full blown)
  - production ready setup
  - landscaper configuration (credentials)
- [ ] Deployers

#### Developer

- [ ] tutorials
- [ ] Blueprint, ComponentDescriptor documentation
- [ ] test locally
  - render
  - inline blueprints etc...

### Level 2 (Landscaper Core)

- [ ] oci artifacts: description, manifests, blobs

ℹ️   Feel free to add additional points

**Comment by schrodit** [comment]
cc @gardener/landscaperctl-maintainers @gardener/landscaper-maintainers

**Comment by In-Ko** [comment]
How do we go on with this one here ? I mean, how should we start creating the new documentation structure, based on the "Chapter Outline" above ? I would suggest we create a readme_new.md, and start working on that one in a new branch. After that has been finished and most relevant and up to date documentation has been created and/or existing docs have been properly linked from this Overview Readme, we can exchange the old one with the new one. Agreed ?

**Comment by schrodit** [comment]
> How do we go on with this one here ? I mean, how should we start creating the new documentation structure, based on the "Chapter Outline" above ? I would suggest we create a readme_new.md, and start working on that one in a new branch. After that has been finished and most relevant and up to date documentation has been created and/or existing docs have been properly linked from this Overview Readme, we can exchange the old one with the new one. Agreed ?

Sounds good to have a new document with the new structure and update that one continuously.
But I would not wait until all the new docs are available (I do not see that in the near future). So I would rather create the new structure with the old linking besides the old one. With the old one containing a link to the new one.

With that we are always up-to-date and users can follow the new, not-yet-finished structure if they want.
WDYT?

**Comment by In-Ko** [comment]
Yes, makes sense. So I will try and go ahead creating a readme_new.md, with the structure above, and link to existing documents which are (from my point of view :) ) still up-to-date. All the other missing docs we will create and properly link from the new readme over the next weeks.

**Comment by In-Ko** [comment]
Current State
- Motivation Chapter Done
- Level 0 (Beginner) more or less done
  - One chapter of the new readme file can be deleted (as the topic is included in the previous chapters already)
  - Link to CLI Documentation about how to use the CLI / install the landscaper needs to be added

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
